spring:
  application:
    name: msvc-account

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_mcc_colin}?options=-c%20TimeZone=UTC
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8081}

feign:
  clients:
    customer:
      name: msvc-customer
      url: http://localhost:8083/customers